# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      

      - name: Deploy
        uses: safe2008/eks-actions@v0.0.4
        env:
          aws_access_key_id: ${{ secrets.AWS_KEYID }}
          aws_secret_access_key: ${{ secrets.AWS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
        with:
          args: kubectl rollout restart deploy/was
