# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      
      - name: Set env
        run: echo "RELEASE_NUMBER=${GITHUB_RUN_NUMBER}" >> GITHUB_ENV

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: gradle chmod
        run: chmod +x ./gradlew
          
      - name: gradle build
        run: ./gradlew build --no-daemon
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: copy war
        run: cp ./build/libs/*.war ./Dockerfile
        
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_${{ env.RELEASE_NUMBER }} ./Dockerfile
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_$GITHUB_RUN_NUMBER
        
      - name: GKE Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTAILS }}'
      
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.LOCATION }}
          project_id: ${{ secrets.PROJECT_ID }}
          
      - name: upload file
        id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: ./build/libs
          destination: ${{ secrets.BUCKET_NAME }}/${{ env.RELEASE_NUMBER }}
          glob: '*.war'
          parent: false
          
      - name: was-deploy restart
        run: kubectl rollout restart deploy/was
