# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEYID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: ${{ secrets.LOCATION }}
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
          
      - name: was-deploy restart
        run: kubectl rollout restart deploy/was
