# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: gradle chmod
        run: chmod +x ./gradlew
          
      - name: gradle build
        run: ./gradlew build --no-daemon
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: copy war
        run: cp ./build/libs/*.war ./Dockerfile
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-north-1
          
      - name: Copy files to the test website with the AWS CLI
        run: aws s3 sync ./build/libs s3://thdus2/${{ github.run_number }}
    
          
      - name: was-deploy restart
        run: kubectl rollout restart deploy/was
