# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: gradle chmod
        run: chmod +x ./gradlew
          
      - name: gradle build
        run: ./gradlew build --no-daemon

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: copy war
        run: cp ./build/libs/*.war ./Dockerfile
        
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_$GITHUB_RUN_NUMBER ./Dockerfile
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_$GITHUB_RUN_NUMBER
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: make .kube directory 
        run: aws eks --region eu-north-1 update-kubeconfig --name thdus
        
      - name: Copy files to the test website with the AWS CLI
        run: aws s3 sync ./build/libs s3://thdus2/$GITHUB_RUN_NUMBER

        
      - name: was-deploy restart
        run: kubectl rollout restart deploy/was
