# This is a basic workflow to help you get started with Actions

name: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set env
        run: echo "RELEASE_VERSION = ${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      
          
      # Runs a single command using the runners shell
      - name: ls
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: echo
        run: echo "This is Checkout"

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
          
      - name: gradle chmod
        run: chmod +x ./gradlew
          
      - name: gradle build
        run: ./gradlew build --no-daemon
            
      - name: check build
        run: ls ./build/libs
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: copy war
        run: cp ./build/libs/*.war ./Dockerfile
        
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_$RELEASE_VERSION ./Dockerfile
        
      - name: docker images
        run: docker images
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_$RELEASE_VERSION
        
      - name: GKE Auth
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTAILS }}'
      
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.LOCATION }}
          project_id: ${{ secrets.PROJECT_ID }}
          
      - name: upload file
        id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: ./build/libs
          destination: ${{ secrets.BUCKET_NAME }}/${{ github.event.head_commit.message }}
          glob: '*.war'
          parent: false
          
      - name: was-deploy restart
        run: kubectl rollout restart deploy/was
